export const startingCategories: { [index: string]: string[] } = {
  Einnahmen: [
    "Lohn und Gehalt",
    "Selbstständigkeit",
    "Dividenden",
    "Vermietung",
    "Kindergeld",
    "Unterhalt",
    "Krankengeld",
    "Arbeitslosengeld",
    "Rente",
    "Sonderzahlungen",
    "Kapitalanlagen",
    "Geschenke",
    "weitere Einnahmen",
  ],
  Wohnen: [
    "Miete",
    "Heizung",
    "Strom",
    "Gas",
    "Wasser",
    "Abwasser",
    "Haushaltswaren",
    "Möbel",
    "Dienstleistungen",
    "Müll",
    "Telefon und Handy",
    "Internet",
    "Fernsehen",
    "Hausratversicherung",
    "Haushaltshilfe",
  ],
  Leben: [
    "Nahrungsmittel",
    "Lieferservice",
    "Restaurant",
    "Getränke",
    "Genussmittel",
    "Reinigungsmittel",
    "Hygieneartikel",
    "Haustiere",
    "Friseur und Kosmetik",
  ],
  Freizeit: [
    "Kinobesuche",
    "Hobbys",
    "Bücher",
    "Zeitschriften",
    "CD",
    "Spiele",
    "Urlaub",
    "Sonstiges",
  ],
  Auto: [
    "Kauf",
    "Raten",
    "Tanken",
    "Steuern",
    "Parken",
    "Versicherung",
    "Autosteuer",
    "Pflege",
    "Wartung",
    "Reperaturen",
  ],
  Sparen: ["zu Notgroschen", "zu Investitionen", "zu Urlaub", "zu Wishlist"],
  Arbeit: ["Fachbücher", "Arbeitskleidung", "Fahrkosten", "Kantine"],
  Sonstiges: [
    "Arzt und Medikamente",
    "Kontogebühren",
    "Kreditraten",
    "Steuerberatung",
    "Steuern",
    "Mobilität",
    "Geschenke",
    "Bekleidung",
    "Versicherungen",
    "Sonstiges",
  ],
};
